apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-vets
  name: petclinic-vets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-vets
  template:
    metadata:
      labels:
        app: petclinic-vets
    spec:
      containers:
        - image: petclinic-vet
          imagePullPolicy: IfNotPresent
          name: petclinic-vets
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "petclinic"
            - name: DB_HOST
              value: "petclinic-db.default.svc.cluster.local"
            - name: DB_NAME
              value: "petclinic"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-vets
spec:
  ports:
    - name: http-ui
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: petclinic-vets
  type: ClusterIP
